blank_issues_enabled: false
contact_links:
  - name: GitHub Comm<u>unity Suppo</u>rt
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://sa.com/javascript:alert(1)
    about: Please report security vulnerabilities here.
